# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'Fitrangi' do
    pod 'SwiftyJSON', '~> 2.2.0'
    pod 'Alamofire', '~> 1.2'
    pod 'SDWebImage', '~> 3.6'
end

target 'FitrangiTests' do

end

